### ISSUE TITLE
Linux以及OSX 在编译后运行皆会出现bad file descriptor的错误

### ISSUE THREAD

**Issue by geekpi** [Adyzng/go-jd#3]
2017/07/13 17:47:30 [ERROR] 加载Cookies失败: EOF
2017/07/13 17:47:30 [ INFO] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2017/07/13 17:47:30 [ INFO] 需要重新登录
2017/07/13 17:47:30 [ INFO] 请打开京东手机客户端，准备扫码登陆:
2017/07/13 17:47:31 [ERROR] 下载二维码失败: write /root/go-jd/jd.qr.png: bad file descriptor
2017/07/13 17:47:31 [ERROR] Failed to persist cookiejar. error write jd.cookies: bad file descriptor.

将程序放到Windows下运行不会，linux 和 osx 均会出现此问题

**Comment by Biercenter** [comment]
我在ubuntu on bash on windows 10也会出现这个，用VPS就正常

**Comment by Adyzng** [comment]
@geekpi @Biercenter 再试试看，创建文件时的权限设置有问题

**Comment by geekpi** [comment]
@Adyzng core/jingdong.go 的16行和22行存在重复定义，去除一个后可以正常运行程序
