### ISSUE TITLE
貌似不能用了

### ISSUE THREAD

**Issue by jackiegk** [Adyzng/go-jd#4]
在添加进购物车之后，订单提交失败

2017/09/21 21:39:14 [ INFO] 登陆成功, P3P: 
2017/09/21 21:39:14 [ INFO] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2017/09/21 21:39:14 [ INFO] 购物车详情>
2017/09/21 21:39:14 [ INFO] 购买  数量  价格      总价      编号      商品
2017/09/21 21:39:14 [ INFO] 总数: 
2017/09/21 21:39:14 [ INFO] 总额: 
2017/09/21 21:39:21 [ INFO] 编号: 531065, 库存: 现货, 价格: 7.90, 链接: https://cart.jd.com/gate.action?pid=531065&pcount=1&ptype=1
2017/09/21 21:39:21 [ INFO] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2017/09/21 21:39:21 [ INFO] 购买商品: 531065
2017/09/21 21:39:28 [ INFO] 成功加入进购物车 2 个 绿箭（DOUBLEMINT）无糖薄荷糖原味薄荷味35粒23.8g单盒金属装（新...
2017/09/21 21:39:28 [ INFO] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2017/09/21 21:39:28 [ INFO] 订单详情>
2017/09/21 21:39:29 [ INFO] 总金额: 
2017/09/21 21:39:29 [ INFO] 　运费: 
2017/09/21 21:39:29 [ INFO] 应付款: 
2017/09/21 21:39:29 [ INFO] 
2017/09/21 21:39:29 [ INFO] 
2017/09/21 21:39:29 [ INFO] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2017/09/21 21:39:29 [ INFO] 提交订单>
2017/09/21 21:39:31 [ INFO] Reponse Data: <!DOCTYPE html>
<html>
………………
[ERROR] 无法解析订单响应数据: invalid character '<' looking for beginning of value

**Comment by Adyzng** [comment]
找过原因了，登陆没成功
京东有时候会认为当前登录有危险，需要手动验证
已修改
